In [1]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [5]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[1, 1])

2nd element on 1st row:  7


In [12]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 0, 2])

9


In [13]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])


[5 6]


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14])
print(arr[1:14:2])

[ 2  4  6  9 11 13]


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14])
print(arr[::2])

[ 1  3  5  7 10 12 14]


In [21]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [22]:
import numpy as np
x = np.array([[1, 2, 3, 4], [11, 12, 13, 14]])
print(x[0:2, 2])

[ 3 13]


In [23]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [2]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [3]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [4]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 42

print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [17]:
n = list(map(int, input("enter the array number :").split(',')))
import numpy as np
arr = np.array(n)
x = arr.view()
x[0] = 42

print(arr)
print(x)

enter the array number : 1, 2, 3, 4, 5


[42  2  3  4  5]
[42  2  3  4  5]


In [10]:
x = list(map(int, input("enter the array number :").split(',')))
import numpy as np
arr = np.array([x])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

enter the array number : 1, 2, 3, 4, 5, 7


None
[[1 2 3 4 5 7]]


In [9]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [9]:
x = list(map(int, input("enter the array number :").split(',')))
import numpy as np
arr = np.array([x], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

enter the array number : 1, 2, 3, 4, 5, 6


[[[[[1 2 3 4 5 6]]]]]
shape of array : (1, 1, 1, 1, 6)


In [8]:
x = list(map(int, input("enter the array number :").split(',')))
import numpy as np
arr = np.array([x], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

enter the array number : 1, 2, 3, 4, 5


[[[[[1 2 3 4 5]]]]]
shape of array : (1, 1, 1, 1, 5)


In [7]:
#Convert the following 1-D array with 12 elements into a 2-D array.
x = list(map(int, input("enter the array number :").split(',')))
y = list(map(int, input("Enter the shape:").split(',')))
import numpy as np
arr = np.array([x])
newarr = arr.reshape(y)
print(newarr)


enter the array number : 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 11, 12, 13, 14, 15
Enter the shape: 5, 3


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 11 12]
 [13 14 15]]


In [18]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
x = list(map(int, input("enter the array number :").split(',')))
y = list(map(int, input("Enter the shape:").split(',')))
import numpy as np
arr = np.array([x])
newarr = arr.reshape(y)
print(newarr)

enter the array number : 1, 6, 2, 3, 4, 5,  7, 8, 9, 10, 11, 12
Enter the shape: 2, 3, 2


[[[ 1  6]
  [ 2  3]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [21]:
#Check if the returned array is a copy or a view:
x = list(map(int, input("enter the array number :").split(',')))
y = list(map(int, input("Enter the shape:").split(',')))
import numpy as np
arr = np.array([x])
print(arr.reshape(y).base)

enter the array number : 1, 2, 3, 4, 5, 6, 7, 8, 9
Enter the shape: 3, 3


[[1 2 3 4 5 6 7 8 9]]


In [22]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements:
x = list(map(int, input("enter the array number :").split(',')))
y = list(map(int, input("Enter the shape:").split(',')))
import numpy as np
arr = np.array([x])
newarr = arr.reshape(y)
print(newarr)#We can not pass -1 to more than one dimension.

enter the array number : 1, 2, 3, 4, 5, 6, 7, 8
Enter the shape: 2, 2, -1


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
#Convert the array into a 1D array:
x = list(map(int, input("enter the array number :").split(',')))
y = list(map(int, input("enter the array number :").split(',')))
z = list(map(int, input("Enter the shape:").split(',')))
import numpy as np
arr = np.array([[x], [y]])
newarr = arr.reshape(z)
print(newarr)

enter the array number : 1, 2, 3
enter the array number : 4, 5, 6
Enter the shape: -1


[1 2 3 4 5 6]


In [32]:
#Iterate on the elements of the following 1-D array:
y = list(map(int, input("enter the array number :").split(',')))
import numpy as np
arr = np.array(y)
for x in arr:
  print(x)


enter the array number : 1, 2, 3


1
2
3


In [29]:
#Iterate on the elements of the following 2-D array:
z = list(map(int, input("enter the array number :").split(',')))
y = list(map(int, input("enter the array number :").split(',')))

import numpy as np

arr = np.array([z, y])

for x in arr:
  print(x)

enter the array number : 1, 2, 3, 4
enter the array number : 5, 6, 7, 8


[1 2 3 4]
[5 6 7 8]


In [34]:
#Iterate on each scalar element of the 2-D array:
a = list(map(int, input("enter the array number :").split(',')))
b = list(map(int, input("enter the array number :").split(',')))
import numpy as np
arr = np.array([a, b])
for x in arr:
  for y in x:
    print(y)

enter the array number : 1, 2, 3, 4
enter the array number : 6, 7, 8, 9 


1
2
3
4
6
7
8
9


In [36]:
a = list(map(int, input("Enter the Array Number:").split(',')))
b = list(map(int, input("Enter the Array Number:").split(',')))
c = list(map(int, input("Enter the Array Number:").split(',')))
d = list(map(int, input("Enter the Array Number:").split(',')))
import numpy as np
arr = np.array([[[a], [b]], [[c], [d]]])
for x in arr:
    print(x)

Enter the Array Number: 1, 2, 3, 4
Enter the Array Number: 3, 4, 5, 6
Enter the Array Number: 3, 5, 6, 7
Enter the Array Number: 4, 5, 6, 8


[[[1 2 3 4]]

 [[3 4 5 6]]]
[[[3 5 6 7]]

 [[4 5 6 8]]]


In [38]:
#Iterate down to the scalars:
a = list(map(int, input("Enter the Array Number:").split(',')))
b = list(map(int, input("Enter the Array Number:").split(',')))
c = list(map(int, input("Enter the Array Number:").split(',')))
d = list(map(int, input("Enter the Array Number:").split(',')))
import numpy as np
arr = np.array([[a, b], [c, d]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

Enter the Array Number: 1, 2, 3, 4
Enter the Array Number: 5, 6, 7, 8
Enter the Array Number: 9, 11, 12, 13
Enter the Array Number: 14, 15, 16, 77


1
2
3
4
5
6
7
8
9
11
12
13
14
15
16
77


In [41]:
a = list(map(int, input("Enter the Array Number :").split(',')))
b = list(map(int, input("Enter the Array Number :").split(',')))
c = list(map(int, input("Enter the Array Number :").split(',')))
d = list(map(int, input("Enter the Array Number :").split(','))) 
import numpy as np
arr = np.array([[[a], [b]], [[c], [d]]])
for x in np.nditer(arr):
    print(x)
    


Enter the Array Number : 1, 2, 3, 4
Enter the Array Number : 2, 3, 6, 7
Enter the Array Number : 7, 8, 9, 5
Enter the Array Number : 6, 8, 5, 9


1
2
3
4
2
3
6
7
7
8
9
5
6
8
5
9


In [52]:
#Iterate through the array as a string:
a = list(map(int, input("Enter the array number:").split(','))) 
import numpy as np
arr = np.array([a])
for x in np.nditer(arr, flags=["buffered"], op_dtypes=['S']):
    print(x)

Enter the array number: 1, 2, 3, 4, 5


b'1'
b'2'
b'3'
b'4'
b'5'


In [56]:
#Iterate through every scalar element of the 2D array skipping 1 element:
b = list(map(int, input("Enter the Array Number :").split(',')))
import numpy as np
arr = np.array([a, b])
for x in np.nditer(arr[:, ::2]):
    print(x)

Enter the Array Number : 1, 2, 3, 4
Enter the Array Number : 5, 6, 7, 8


1
3
5
7


In [59]:
#Enumerate on following 1D arrays elements:
a = list(map(int, input("Enter the Array Number :").split(',')))
import numpy as np
arr = np.array([a])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

Enter the Array Number : 1, 2, 3


(0, 0) 1
(0, 1) 2
(0, 2) 3


In [ ]:
a = list(map(int, input("Enter the Array Number :").split(',')))
import numpy as np
arr = np.array([a, b]
for x, idx in np.ndenumerate(arr):
    print(x, idx)